train_annotations: "C:/Users/xavid/Desktop/dataset/mjsynth/mnt/ramdisk/max/90kDICT32px/annotation_val.txt"
test_annotations: ""
images_dir: "C:/Users/xavid/Desktop/dataset/mjsynth/mnt/ramdisk/max/90kDICT32px"
